trigger:
- main  # Adjust the branch name as needed

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Or whichever Node.js version you're using
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install NPM dependencies'

- script: npm run cypress:run
  displayName: 'Run Cypress tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/cypress/results/*.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish Cypress Test Results'
