name: Cypress E2E Tests

on:
  push:
    branches:
      - main  # Run tests on push to main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Specify Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Cache npm dependencies

      - name: Install dependencies
        run: npm ci  # Install dependencies using npm

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          build: npm run build  # If you have a build step
          start: npm start      # If you need to start a server before testing
          wait-on: 'http://localhost:3000'  # Adjust to match your server's URL
          wait-on-timeout: 60  # Timeout for waiting for the server to start

      - name: Upload Cypress screenshots and videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
